<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.fuse.client.model.FuseApiErrorDataTest" tests="3" skipped="0" failures="0" errors="0" timestamp="2023-09-12T14:49:06" hostname="Mac-1694529973771.local" time="0.019">
  <properties/>
  <testcase name="aggregatorTest()" classname="org.fuse.client.model.FuseApiErrorDataTest" time="0.0"/>
  <testcase name="testFuseApiErrorData()" classname="org.fuse.client.model.FuseApiErrorDataTest" time="0.0"/>
  <testcase name="errorsTest()" classname="org.fuse.client.model.FuseApiErrorDataTest" time="0.018"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
